### ISSUE TITLE
Barcode format ?

### ISSUE THREAD

**Issue by x4080** [facundomedica/fast_qr_reader_view#43] opened 2019-05-24 03:26 UTC
Hi, what format do we have to use for regular groceries barcode ? I tried code39, code128 and code93 cannot read the barcode

Thanks,

PS for QR code works flawlessly

Permission problem @start, after allowed, it will crash, and next time app works fine, any issue on this?

**Comment by x4080** [comment] 2019-05-24 03:37
Found it, its using ean8 and ean13 I think, I found that when using code39 or code128, sometimes the snackbar output code39 or code128, how can we determine the format and the content ?

Thanks

**Comment by jmeinlschmidt** [comment] 2019-06-10 10:49
Hey!,

all available `CodeFormats` can be found in the source code.

see `https://github.com/facundomedica/fast_qr_reader_view/blob/master/lib/fast_qr_reader_view.dart`

```
var _availableFormats = {
  CodeFormat.codabar: 'codabar', // Android only
  CodeFormat.code39: 'code39',
  CodeFormat.code93: 'code93',
  CodeFormat.code128: 'code128',
  CodeFormat.ean8: 'ean8',
  CodeFormat.ean13: 'ean13',
  CodeFormat.itf: 'itf', // itf-14 on iOS, should be changed to Interleaved2of5?
  CodeFormat.upca: 'upca', // Android only
  CodeFormat.upce: 'upce',
  CodeFormat.aztec: 'aztec',
  CodeFormat.datamatrix: 'datamatrix',
  CodeFormat.pdf417: 'pdf417',
  CodeFormat.qr: 'qr',
};
```

Barcode format depends on issuing authority such as [GS1](https://www.gs1.org/standards/barcodes) etc. However, you have to be sure about what is your application going to scan. Every business can use different formats. The most common is EAN code format.

Your next questing about getting the format `onCodeRead` is a duplicate of [#2](https://github.com/facundomedica/fast_qr_reader_view/issues/2). In short, author doesn't have time to work on this. So there is a chance for everyone to open his own pull request including this feature. In order to get the format, there is a change needed to be made in [these files](https://github.com/facundomedica/fast_qr_reader_view/blob/master/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java).

Hope I helped you.

**Comment by x4080** [comment] 2019-06-11 02:40
@jmeinlschmidt  thanks !!

**Comment by SoftWyer** [comment] 2019-12-26 19:28
You can also use all formats just by passing in `CodeFormat.values` as the formats argument.

**Comment by facundomedica** [comment] 2021-07-18 00:01
Thank you guys!

**Closed as completed by facundomedica** 2021-07-18 00:01 UTC
