### ISSUE TITLE
Crash on permission response

### ISSUE THREAD

**Issue by ThomasEcalle** [facundomedica/fast_qr_reader_view#41] opened 2019-05-18 21:37 UTC
Hi,

First of all, thank you a lot for this library ! I was looking fur such a customizable QrCode reader in flutter :)

I just want to make you know about a crash, in the example application, on Android, when we click on permission request dialog.

Neither we click on "accept" or "deny", we got : 

```
FATAL EXCEPTION: main
E/AndroidRuntime(19537): Process: co.apperto.fastqrreaderviewexample, PID: 19537
E/AndroidRuntime(19537): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {co.apperto.fastqrreaderviewexample/co.apperto.fastqrreaderviewexample.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime(19537): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime(19537): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime(19537): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(19537): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(19537): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(19537): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(19537): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19537): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(19537): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(19537): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19537): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(19537): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(19537): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime(19537): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(FastQrReaderViewPlugin.java:330)
E/AndroidRuntime(19537): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:203)
E/AndroidRuntime(19537): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:127)
E/AndroidRuntime(19537): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime(19537): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
E/AndroidRuntime(19537): 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
E/AndroidRuntime(19537): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
```

I tried to understand what causes it in Android plugin but found nothing :/

**Comment by facundomedica** [comment] 2019-05-21 13:19
Please check if it was fixed with the latest PR merged, thanks!

**Comment by xcoinmakers-fukuda** [comment] 2019-05-22 08:41
@facundomedica
I tried to use this code, but it still crashed with the same error.

**Comment by xalabax** [comment] 2019-05-28 18:32
D/AndroidRuntime(17750): Shutting down VM
E/AndroidRuntime(17750): FATAL EXCEPTION: main
E/AndroidRuntime(17750): Process: com.lan4.lan4, PID: 17750
E/AndroidRuntime(17750): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.lan4.lan4/com.lan4.lan4.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime(17750): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
E/AndroidRuntime(17750): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4424)
E/AndroidRuntime(17750): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(17750): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(17750): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(17750): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
E/AndroidRuntime(17750): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17750): 	at android.os.Looper.loop(Looper.java:280)
E/AndroidRuntime(17750): 	at android.app.ActivityThread.main(ActivityThread.java:6706)
E/AndroidRuntime(17750): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17750): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(17750): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(17750): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime(17750): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(FastQrReaderViewPlugin.java:330)
E/AndroidRuntime(17750): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:203)
E/AndroidRuntime(17750): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:128)
E/AndroidRuntime(17750): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime(17750): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
E/AndroidRuntime(17750): 	at android.app.Activity.dispatchActivityResult(Activity.java:7458)
E/AndroidRuntime(17750): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4375)

Sony Xperia ZX1, 9.0

**Comment by xesun** [comment] 2019-06-09 15:16
E/AndroidRuntime(27099): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {mn.verus.restaurants/mn.verus.restaurants.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime(27099): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
E/AndroidRuntime(27099): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4964)
E/AndroidRuntime(27099): 	at android.app.ActivityThread.access$1600(ActivityThread.java:221)
E/AndroidRuntime(27099): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
E/AndroidRuntime(27099): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27099): 	at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(27099): 	at android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime(27099): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27099): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(27099): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/AndroidRuntime(27099): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime(27099): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(FastQrReaderViewPlugin.java:330)
E/AndroidRuntime(27099): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime(27099): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:127)
E/AndroidRuntime(27099): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime(27099): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7263)
E/AndroidRuntime(27099): 	at android.app.Activity.dispatchActivityResult(Activity.java:7141)

**Comment by ghost** [comment] 2019-06-11 05:36
I reverted to this commit **e82f1a8bf4f596c21e2fe5801c4dd15942b5e67c** and works!

**Comment by szotp** [comment] 2019-06-19 06:40
Another workaround: `await requestCameraPermission` before `await availableCameras`.

**Comment by bachbonglong** [comment] 2019-07-03 06:57
> Another workaround: `await requestCameraPermission` before `await availableCameras`.

But if you click deny . CRASH  appear and stop app

**Comment by worawutt** [comment] 2019-07-11 04:44
> > Another workaround: `await requestCameraPermission` before `await availableCameras`.
> 
> But if you click deny . CRASH appear and stop app

There is PermissionStatus return from await requestCameraPermission, Check it before call  availableCameras.

**Comment by worawutt** [comment] 2019-07-13 08:48
> Another workaround: `await requestCameraPermission` before `await availableCameras`.

for addition info that I found.
await requestionCameraPermission is woking when use with Android 6.0 and above.
If Android version below 6, No need to use it. Just call await availableCameras.

**Comment by facundomedica** [comment] 2021-07-18 00:05
The example got fixed 👌

**Closed as completed by facundomedica** 2021-07-18 00:05 UTC
Labels: help wanted, good first issue
